### ISSUE TITLE
Order Donors in the TabList after Staff

### ISSUE THREAD

**Issue by VladyslavLukyanenko** [Electroid/PGM#273] opened 2020-01-29 16:10 UTC
Order Donors in the TabList after Staff, like in OCN, Staff>Dux>Centurion>Optio>Regular

**Comment by Brottweiler** [comment] 2020-01-29 16:42
I don't know who it was, probably pablete, who asked if players with premium perms should be higher in the list. Personally I kind of liked how they weren't higher in the list. Staff being higher in the list makes it easier to notice them but not sure if premium players should be.

If it's a bug then it should be fixed but I don't know if it is a bug?

**Comment by Meeples10** [comment] 2020-01-29 16:55
Maybe it could be implemented with a config option to enable it?

**Comment by Pablete1234** [comment] 2020-01-29 17:03
This is not a bug, this is just a missing feature. Currently pgm only sorts by the staff permission node. Should probably add a feature to the defined groups to allow them being sorted or not

**Comment by Xerocoles** [comment] 2020-01-30 04:00
I think it's good to have donors higher too, just gives more donation incentives, as well as looking cleaner

**Closed** 2020-05-02 15:35 UTC
Labels: feature, reintroduce
