### ISSUE TITLE
Spawner module is not documented

### ISSUE THREAD

**Issue by Pugzy** [Electroid/PGM#455] opened 2020-05-04 17:08 UTC
I understand it has just been merged but I'm making this issue to ensure it remains on our radars.

New changes and modules without documentation will not be used by map makers.
Now is the optimal time to create this documentation as its functionality is fresh in our heads.

**Comment by EricZeiberg** [comment] 2020-05-04 19:42
Duplicate of #447

**Closed** 2020-05-04 21:07 UTC
