### ISSUE TITLE
Only the first defined spawn position is used

### ISSUE THREAD

**Issue by RuedigerLP** [Electroid/PGM#103] opened 2019-12-05 16:29 UTC
i noticed it on "Toss Up" it also happened on other ffa maps, i dont know if it only happens on ffa maps.

**Comment by Xerocoles** [comment] 2019-12-06 03:43
Yeah I mentioned this in a previous issue but it was closed because the first part of what I was mentioning then just turned out to just be a mistake on my part, but this part was still very true.  FFAs, and especially Rage FFAs, are practically unplayable until this is fixed.

**Comment by Pugzy** [comment] 2019-12-08 15:39
Just investigated this with the "Toss Up" map and spawns seem to be working as intended.

In FFA all spawn points are checked with a `SpreadPointProvider`.
https://github.com/Electroid/PGM/blob/de9bf2b10e1d6e8ff9758166ad1d707f68974dff/src/main/java/tc/oc/pgm/points/SpreadPointProvider.java#L20 

This finds the best spawn point based on the distance of enemies away from them, the one with the highest distance is used. When testing this with no other players the same point `x=-22.5,y=11.0,z=-86.5,pitch=0.0,yaw=-85.0` is always used as it is the first tested and remains greater than/equal to subsequent spawn distance checks.

When testing this with 2+ players points are selected based on the distance which changes as players move around the map so different spawn points are used.

Do you have more info about your testing environment?
Have you tested this with multiple players?

**Comment by Xerocoles** [comment] 2019-12-10 04:46
Seems to work now, not sure what happened cause I think I had been using the updated code, but it seems to work for me now so that's good (or maybe it doesn't work when it's just one person, which wouldn't matter anyways)

**Comment by RuedigerLP** [comment] 2019-12-10 15:15
I tested alone.

**Comment by Electroid** [comment] 2019-12-10 16:09
Is this an issue or not?

**Comment by Brottweiler** [comment] 2019-12-10 16:25
I tested this now again on Iteritus. Spawns work as intended, but the OP refers to FFA maps and Pugzy tested the affected map mentioned in the OP and it seems to work there as well, and Xerocoles confirms it. Does not seem like an issue.

**Comment by Xerocoles** [comment] 2019-12-11 22:42
Yea now i can definitely clarify - it only happens when you're in the FFA match alone, which is how I originally saw it from xml stuff ofc

**Comment by Brottweiler** [comment] 2019-12-12 14:07
Sounds like a bug even if it's very low priority if it only affects FFA maps when there's 1 player.

**Comment by Pablete1234** [comment] 2019-12-14 01:02
How is it a bug? I feel like it's intended behaviour. Like @Pugzy mentioned, pgm finds the "safest" point (the one furthest away from other players), if you're alone that point doesn't change, and this feels like expected behaviour to me.
Am i missing something else? should it have a different behaviour?

**Comment by Xerocoles** [comment] 2019-12-14 01:15
I guess it's more or less a bug because it's deciding to always pick the first spawn rather than a random spawn when there's only one person playing.  I think the only reason this matters is for people testing their XMLs -- they might think it's an error in their XML when in reality it would work completely fine.

**Comment by Pugzy** [comment] 2019-12-15 15:48
I have added this to a personal branch 2e156deca4f98fdfbcb87de3f02177278cca5a42, however, this only really works for when there's a single player as the distance is almost certainly not going to be equal in any other match scenario.

Happy to create a PR if the changes are deemed necessary otherwise I'd close this issue. Open to further discussion regarding implementation in the future but we should try to keep the issue list clean.

**Comment by Pugzy** [comment] 2019-12-15 17:19
Created a pull request https://github.com/Electroid/PGM/pull/115 for this with the change suggested by Molka.

**Closed** 2020-01-24 17:50 UTC
Labels: bug
