### ISSUE TITLE
You move very fast after you die

### ISSUE THREAD

**Issue by RuedigerLP** [Electroid/PGM#104] opened 2019-12-06 23:09 UTC
I think players are supposed to be forzen after they die, but when this bug occurs u have a lot of momentum in the direction you are looking.

**Comment by TheMolkaPL** [comment] 2019-12-06 23:11
Might be related to #89

**Comment by Brottweiler** [comment] 2019-12-07 15:26
Duplicate of https://github.com/Electroid/PGM/issues/89.

**Closed by Brottweiler** 2019-12-07 15:26 UTC
